namespace Minesweeper.Core.Models;

/// <summary>
/// Game data entity class
/// </summary>
public class Game
{
    /// <summary>
    /// Game ID, generated by DB
    /// </summary>
    public Guid GameId { get; set; }
    /// <summary>
    /// Game field width
    /// </summary>
    public int Width { get; set; }
    /// <summary>
    /// Game field height
    /// </summary>
    public int Height { get; set; }
    /// <summary>
    /// Mines quantity on field
    /// </summary>
    public int MinesCount { get; set; }

    /// <summary>
    /// Game is completed
    /// </summary>
    public bool IsCompleted { get; set; }

    /// <summary>
    /// Game field, first dim is Y, second is X
    /// </summary>
    public string[][] Field { get; set; }

    /// <summary>
    /// How many cells are opened
    /// </summary>

    public int TurnNumber { get; set; }

}
