using System.Text.Json.Serialization;

namespace Minesweeper.Core.Models;

/// <summary>
/// DTO class with response information about game condition
/// </summary>
public class GameDTO
{
    /// <summary>
    /// Game ID, generated by DB
    /// </summary>
    [JsonPropertyName("game_id")]
    public string GameId { get; set; }

    /// <summary>
    /// Game field width
    /// </summary>
    [JsonPropertyName("width")]
    public int Width { get; set; }

    /// <summary>
    /// Game field height
    /// </summary>
    [JsonPropertyName("height")]
    public int Height { get; set; }

    /// <summary>
    /// Mines quantity on field
    /// </summary>
    [JsonPropertyName("mines_count")]
    public int MinesCount { get; set; }

    /// <summary>
    /// Game is completed
    /// </summary>
    [JsonPropertyName("completed")]
    public bool IsCompleted { get; set; }

    /// <summary>
    /// Game field, first dim is Y, second is X
    /// </summary>
    [JsonPropertyName("field")]
    public string[][] Field { get; set; }

}
